var op1,op2,op1,op2,led;
var array1=[];//green
var array2=[];//red
var j=0;
var btn1,btn2;

function startMotor(id)
{
	if(id==1)
	{
		op1=document.getElementById("op1");
		op2=document.getElementById("op2");  
		led=document.getElementById("mtr1");
		btn1=document.getElementById("start2");
		btn2=document.getElementById("start3");
		array1=[1,3,4,5,6,9,11,14,16,17];
		array2=[7,8,10,12,13,15];
		document.getElementById("stop1").disabled=false;
		j=2;
		document.getElementById("arrow").style.top="155px";
	}
	if(id==2)
	{
		op1=document.getElementById("op3");
		op2=document.getElementById("op4");  
		led=document.getElementById("mtr2");
		btn1=document.getElementById("start1");
		btn2=document.getElementById("start3");
		array1=[1,4,6,8,9,10,11,13,18,19];
		array2=[2,3,5,12,14,15];
		document.getElementById("stop2").disabled=false;
		j=7;
		document.getElementById("arrow").style.top="275px";
	}
	if(id==3)
	{
		op1=document.getElementById("op5");
		op2=document.getElementById("op6");  
		led=document.getElementById("mtr3");
		array1=[1,3,6,8,11,13,14,15,20,21];
		array2=[2,4,5,7,9,10];
		document.getElementById("stop3").disabled=false;
		btn1=document.getElementById("start2");
		btn2=document.getElementById("start1");
		j=12;
		document.getElementById("arrow").style.top="397.5px";
	}
	document.getElementById("arrow").style.visibility="visible";
	document.getElementById("arrow").style.transformOrigin="center";
	document.getElementById("arrow").style.animation="rotate 0.5s linear infinite";
	
	start(op1,op2,led,array1,array2,j,btn1,btn2);
}

function start(op1,op2,led,array1,array2,j,btn1,btn2)
{
	op1.style.visibility="visible";
	op2.style.visibility="visible";
	led.style.visibility="visible";
	btn1.disabled=true;
	btn2.disabled=true;
	for(i=0;i<array1.length;i++)
	{
		document.getElementById("bit"+array1[i]).style.backgroundColor="#00AC00";
	}
	for(i=0;i<array2.length;i++)
	{
		document.getElementById("bit"+array2[i]).style.backgroundColor="#FF0000";
	}
	document.getElementById("bit"+j).style.backgroundColor="#00AC00";
	setTimeout(function()
	{
		document.getElementById("bit"+j).style.backgroundColor="#FF0000";
	},750);
}

function stop(id)
{
	document.getElementById("arrow").style.transformOrigin="";
	document.getElementById("arrow").style.animation="";
	document.getElementById("arrow").style.visibility="hidden";
	op1.style.visibility="hidden";
	op2.style.visibility="hidden";
	btn1.disabled=false;
	btn2.disabled=false;
	for(i=1;i<=15;i++)
	{
		if(id==1)
		{
			document.getElementById("mtr1").style.visibility="hidden";
			document.getElementById("stop1").disabled=true;
			if(i==1)
			{
				document.getElementById("bit1").style.backgroundColor="#FF0000";
				setTimeout(function()
				{
					document.getElementById("bit1").style.backgroundColor="#00AC00";
				},750);
			}
		}
		else 
		{
			document.getElementById("bit1").style.backgroundColor="#00AC00";
		}
		if(id==2)
		{
			document.getElementById("mtr2").style.visibility="hidden";
			document.getElementById("stop2").disabled=true;
			if(i==6)
			{
				document.getElementById("bit6").style.backgroundColor="#FF0000";
				setTimeout(function()
				{
					document.getElementById("bit6").style.backgroundColor="#00AC00";
				},750);
			}
		}
		else 
		{
			document.getElementById("bit6").style.backgroundColor="#00AC00";
		}
		if(id==3)
		{
			document.getElementById("mtr3").style.visibility="hidden";
			document.getElementById("stop3").disabled=true;
			if(i==11)
			{
				document.getElementById("bit11").style.backgroundColor="#FF0000";
				setTimeout(function()
				{
					document.getElementById("bit11").style.backgroundColor="#00AC00";
				},750);
			}
		}
		else 
		{
			document.getElementById("bit11").style.backgroundColor="#00AC00";
		}
		if(i==3||i==4||i==8||i==9||i==13||i==14)
		{
			document.getElementById("bit"+i).style.backgroundColor="#00AC00";
		}
		if(i==2||i==5||i==7||i==10||i==12)
		{
			document.getElementById("bit"+i).style.backgroundColor="#FF0000";
		}
	}
	for(i=15;i<=21;i++)
	{
		document.getElementById("bit"+i).style.backgroundColor="#FF0000";
	}
}